#!/bin/bash

PPPHOME="$HOME/ppp"
PROJECTS=`ls $PPPHOME/programming/programs`

usage() {
  echo "usage:" 
  echo "  $ export_script [project name]"
}

# 1) check for command line args
if [ "$#" -eq 0 ]; then
  usage;
  exit 1;
fi

echo $PROJECTS
exit 0;
