.PHONY: all init install clean uninstall

all: install

init:
	mkdir -p ~/.export_projects

install:
	cp export_project /bin/

clean:
	rm -rf ~/.export_projects

uninstall:
	rm -f /bin/export_project
