#!/bin/bash 

read fst
if [[ $fst -eq 0 ]]; then
  pico2wave -w tmp.wav \"$@\" &>/dev/null  
  exit 0;
fi

file=$1
echo zipwave: $file
shift;
echo zipwave: $@

pico2wave -w next.wav \"$@\" &>/dev/null
sox tmp.wav next.wav out.wav
mv out.wav tmp.wav

#yes Y | ffmpeg \
#  -i $file \
#  -i next.wav \
#  -filter_complex '[0:0][1:0][2:0][3:0]concat=n=2:v=0:a=1[out]' \
#  -map '[out]' $file &>/dev/null

rm next.wav
