#!/bin/bash

file=$1
echo zipwave: $file
shift;
echo zipwave: $@

pico2wave -w next.wav \"$@\" &>/dev/null
sleep 1;

yes Y | ffmpeg \
  -i $file \
  -i next.wav \
  -filter_complex '[0:0][1:0]concat=n=2:v=0:a=1[out]' \
  -map '[out]' $file &>/dev/null

rm next.wav
