#!/bin/bash 
echo "stripping photos of metadata..."
files=$(find website_content/ \
        -type f \
        -regextype posix-egrep \
        -regex ".*\.(jpg|jpeg|png|gif|mp4)$" \
        | xargs -L 1)

for file in $files; do
  echo removing metadata for $file;
  exiftool -all= $file
  2>/dev/null rm "$file"_original
  if [ -z $? ]; then 
    echo removing "$file"_original
  fi
done  

echo "creating and exporting website_content.zip to $1..."
zip -r website_content website_content
sleep 1
if [ "$1" == "" ]; then
  echo "no target directory specified, exporting to \$HOME"
  mv website_content.zip ~
else
  mv website_content.zip $1
fi
